# Generated by Django 2.0.5 on 2018-05-25 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServerName', models.CharField(max_length=32)),
                ('IP', models.CharField(max_length=64)),
                ('RemotePort', models.IntegerField()),
                ('SuperUser', models.CharField(max_length=32)),
                ('SuperUserPass', models.CharField(max_length=64)),
                ('Environment', models.CharField(max_length=32)),
                ('OSType', models.CharField(max_length=32)),
                ('OSVersion', models.CharField(max_length=32)),
                ('Zabbix', models.BooleanField()),
                ('Salt', models.BooleanField()),
                ('Jumpserver', models.BooleanField()),
                ('Keepass', models.BooleanField()),
                ('Note', models.CharField(max_length=1024)),
            ],
        ),
    ]
