# Generated by Django 2.0.5 on 2018-05-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostinfo',
            options={'verbose_name': '主机信息', 'verbose_name_plural': '主机信息'},
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='Environment',
            field=models.CharField(max_length=32, verbose_name='使用环境'),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='IP',
            field=models.CharField(max_length=64, verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='Jumpserver',
            field=models.BooleanField(verbose_name='是否加入堡垒机'),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='Keepass',
            field=models.BooleanField(verbose_name='是否记录密码'),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='Note',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注信息'),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='OSType',
            field=models.CharField(max_length=32, verbose_name='操作系统类型'),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='OSVersion',
            field=models.CharField(max_length=32, verbose_name='操作系统版本'),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='RemotePort',
            field=models.IntegerField(verbose_name='远程端口'),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='Salt',
            field=models.BooleanField(verbose_name='是否加入自动化运维'),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='ServerName',
            field=models.CharField(max_length=32, verbose_name='服务器名称'),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='SuperUser',
            field=models.CharField(max_length=32, verbose_name='超级用户名'),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='SuperUserPass',
            field=models.CharField(max_length=64, verbose_name='超级用户密码'),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='Zabbix',
            field=models.BooleanField(verbose_name='是否加入监控'),
        ),
    ]
