# Generated by Django 2.0.5 on 2018-05-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManagement', '0004_hostenv_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GroupName', models.CharField(max_length=32, verbose_name='分组名称')),
                ('Note', models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注信息')),
            ],
        ),
    ]
