# Generated by Django 2.0.5 on 2018-05-31 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManagement', '0005_hostgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostinfo',
            name='HostGroup',
            field=models.CharField(default='', max_length=32, verbose_name='主机分组'),
        ),
    ]
