# Generated by Django 2.0.5 on 2018-06-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManagement', '0006_hostinfo_hostgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostAndHGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServerName', models.CharField(max_length=32, verbose_name='服务器名称')),
                ('GroupName', models.CharField(max_length=32, verbose_name='分组名称')),
            ],
        ),
    ]
