# Generated by Django 2.0.5 on 2018-06-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManagement', '0009_auto_20180601_1639'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HostAndHGroup',
        ),
        migrations.RemoveField(
            model_name='hostgroup',
            name='GroupName',
        ),
        migrations.AddField(
            model_name='hostgroup',
            name='GroupName',
            field=models.ManyToManyField(to='AssetManagement.HostInfo'),
        ),
    ]
