# Generated by Django 2.0.5 on 2018-07-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManagement', '0014_physicalserver'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalserver',
            name='Owner',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='所有者'),
        ),
        migrations.AlterField(
            model_name='physicalserver',
            name='ExpireData',
            field=models.DateField(max_length=32, verbose_name='维保过期时间'),
        ),
    ]
