# Generated by Django 2.0.5 on 2018-07-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManagement', '0015_auto_20180702_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physicalserver',
            name='ManageIP',
        ),
        migrations.AddField(
            model_name='physicalserver',
            name='ManageURL',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='登录URL'),
        ),
        migrations.AlterField(
            model_name='physicalserver',
            name='CPU',
            field=models.CharField(max_length=32, verbose_name='CPU'),
        ),
        migrations.AlterField(
            model_name='physicalserver',
            name='Memory',
            field=models.CharField(max_length=32, verbose_name='内存'),
        ),
    ]
