# Generated by Django 2.0.5 on 2018-07-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManagement', '0016_auto_20180702_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalserver',
            name='Note',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注信息'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='Name',
            field=models.CharField(max_length=32, verbose_name='型号名称'),
        ),
    ]
