# Generated by Django 2.0.5 on 2018-07-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManagement', '0017_auto_20180702_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalserver',
            name='SN',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='序列号'),
        ),
    ]
