# Generated by Django 2.0.5 on 2018-08-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManagement', '0019_auto_20180703_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostinfo',
            name='Use',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='是否使用'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='ManageIP',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='管理IP'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='Password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='密码'),
        ),
    ]
