# Generated by Django 2.0.5 on 2018-08-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManagement', '0020_auto_20180813_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkdevice',
            name='ConsolePassword',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Console管理密码'),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='WebManageIP',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Web远程管理IP'),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='WebPassword',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Web远程管理密码'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='ManageIP',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='普通远程管理IP'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='Password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='普通远程密码'),
        ),
    ]
