# Generated by Django 2.0.5 on 2018-08-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManagement', '0021_auto_20180813_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkdevice',
            name='ManageUser',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='普通远程管理用户'),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='WebManageUser',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Web远程管理用户'),
        ),
    ]
